### ISSUE TITLE
Suggestions | Questions | So on :)

### ISSUE THREAD

**Issue by RolEYder** [hinton-lang/Hinton#1]
Nice project! :+1:  I would like to contribute but I don't know what stages are still in process :disappointed: , so I recommend you define a to-do list :notebook:  of what parts are still in development.

In another sense, what is the purpose of this new "programming language"? The question is based upon exists a lot of programming languages ​​with behaviors like this.

And finally, here some suggestions that I considered needed:
* :mechanic:  Build setup installer to automate the installation. 
* :page_with_curl:  Realize some benchmarks to prove performance stuff in the programming languages ​​regardless of the hardware of the pc tested (papel).
*  :notebook: Do a To-Do list of what stages are still in process.

:eye: **DISCLAIMER**: Maybe this project it's just a toy project, so my suggestions maybe get out of context, if that case, obviate that.

**Comment by faustotnc** [comment]
Hey @RolEYder! Thank you for the suggestions and questions. As of right now, this project is a way for me to get involved in writing compilers and interpreters. It is a subject that I would like to learn more about since we as programmers often take for granted how much goes behind the scenes when writing new programs. I am not very proficient with writing programs in C, let alone bytecode or other low-level machine code. My next college class (Intro. to Computer Architecture - UNCC) will introduce me to those subjects. But as of now, I have zero experience.

**The current state of the project**: The project is still in the "pre-development" stages. This means that I am (1) still trying to learn how it all works, and (2) I am also figuring out what the syntax of the language will be. Since I am still learning, anything about the language can change as I get more experience. To give you an exact place of where the project is, I just finished translating - for the most part - the lexer from Java to C.

**What is the purpose of Hinton?**: This is a good question. There are so many other well built, well established, and well-defined languages out there that there is really no point in creating a new one. I am not trying to take any other programming language out of business with Hinton (mostly because I can't 😖), instead, I am just writing an interpreter to improve my knowledge of computer systems. My vision for Hinton right now is to make it a general-purpose programming language that can be a second option for programmers that do not like Python's syntax.

Since you suggested benchmarking, I will go ahead and tell you: the current Java version is SLOW. Too slow to be used in any context. That is why I have started to translate it from Java to C.

The base code for this project can be found in this awesome book by Bob Nystrom: https://craftinginterpreters.com/. If you are interested in contributing, I suggest that you read (or at least scan through) the book so that you can get an idea of why some of the code looks the way it does.

I appreciate your suggestions. I will leave this issue open until I officially address your questions in the project's description.

**Now concerning your disclaimer**: Yes, Hinton is a toy project. But you never know...
